version: '3.8'

services:
   jenkins:
     image: jenkins/jenkins:latest
     restart: 'unless-stopped'
     privileged: true
     user: root
     ports:
       - '8080:8080'
       - '50000:50000'
     expose:
       - '8080'
     environment:
       - JENKINS_ADMIN_USERNAME=admin
       - JENKINS_ADMIN_PASSWORD=secretpassword
     volumes:
       - ./data:/var/jenkins_home
       - ./scripts/:/usr/share/jenkins/ref/init.groovy.d/
