version: '3.8'

services:
   pg:
    image: postgres:15
    networks:
      - db-net
    restart: 'unless-stopped'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - ./data:/var/lib/postgresql/data/pgdata
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "app"]
      interval: 20s
      timeout: 10s
      retries: 10
